import { chromium } from "playwright";
const run = async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  await page.goto("http://localhost:4173/", { waitUntil: "networkidle" });
  await page.getByTestId("new-project").click();
  await page.getByTestId("project-name-input").fill("调试");
  await page.getByTestId("project-brief-input").fill("海军蓝加琥珀金");
  await page.getByTestId("create-project-submit").click();
  await page.getByTestId("board-generate").click();
  await page.locator('[data-testid^="board-candidate-"]').first().waitFor();
  await page.locator('[data-testid^="board-candidate-"] [data-testid="action-set-anchor"]').first().click();
  await page.getByTestId("anchor-badge").waitFor();
  await page.getByTestId("step-nav-page").click();
  await page.getByTestId("add-page-toggle").click();
  await page.getByTestId("page-slug-input").fill("dashboard");
  await page.locator('[data-testid="add-page-form"] textarea, [data-testid="add-page-form"] input[type="text"]').last().fill("顶部4张指标卡");
  await page.getByTestId("add-page-submit").click();
  await page.getByTestId("page-generate").first().click();
  await page.locator('[data-testid^="page-candidate-"]').first().waitFor();
  await page.locator('[data-testid^="page-candidate-"] [data-testid="action-pick"]').first().click();
  await page.locator('[data-testid$="picked-badge"]').first().waitFor();
  await page.getByTestId("step-nav-component").click();
  await page.getByTestId("add-component-toggle").click();
  await page.getByTestId("component-name-input").fill("button-set");
  await page.getByTestId("add-component-submit").click();
  await page.waitForTimeout(1200);
  await page.screenshot({ path: "e2e/screenshots/dbg-component-add.png" });
  const toast = await page.getByTestId("toast-viewport").textContent().catch(() => "(no toast)");
  console.log("toast:", toast?.slice(0, 200));
  const ids = await page.locator("[data-testid]").evaluateAll(els => els.map(e => e.getAttribute("data-testid")));
  console.log([...new Set(ids)].filter(i => i.includes("component") || i.includes("item")).join("\n"));
  await browser.close();
};
run().catch(e => { console.error("FAIL:", e.message); process.exit(1); });
