import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import brandTemplateJson from "../../../templates/brand-identity-lite.json";
import boardTemplateJson from "../../../templates/board-design-system.json";
import componentTemplateJson from "../../../templates/component-sheet-grid.json";
import landingTemplateJson from "../../../templates/page-landing-sections.json";
import pageTemplateJson from "../../../templates/page-ui-standard.json";
import {
  composeBoardPrompt,
  composeComponentPrompt,
  composePagePrompt,
  type PromptProject,
  type TemplateJson,
} from "@/lib/generation/prompt";

/**
 * Golden parity harness (C6): the checked-in files under `__goldens__/` are
 * GENERATED BY THE RUST ENGINE (crates/rudder-core/src/prompt.rs `mod
 * goldens`, the CLI/desktop single source of truth). Each test asserts the
 * TS port reproduces a golden byte-for-byte, so engine drift between the
 * CLI and the SDK path fails here.
 *
 * Regenerate after an INTENDED engine/template change (then mirror the
 * fixture/template updates on BOTH sides in the same commit):
 *
 *     RUDDER_UPDATE_GOLDENS=1 cargo test -p rudder-core --lib goldens
 */

const GOLDENS_DIR = path.join(path.dirname(fileURLToPath(import.meta.url)), "__goldens__");

// --- fixtures: MIRROR crates/rudder-core/src/prompt.rs fixture_a/fixture_b ---

const projectA: PromptProject = {
  name: "远洋航运 SaaS",
  brandBrief: "远洋航运行业，专业克制",
  styleBrief: "海军蓝 + 黄铜点缀，圆角 8px，紧凑密度",
  canvasW: 1536,
  canvasH: 1024,
};

const projectB: PromptProject = {
  name: "  学术写作台  ",
  brandBrief: "论文写作工作流",
  styleBrief: "",
  negativeHints: ["不要通用放大镜图标", "no dark mode"],
  canvasW: 1024,
  canvasH: 1364,
};

const pageA = { slug: "dashboard", brief: "顶部指标卡x4，中部折线图区" };
const pageB = {
  slug: "landing",
  brief: "导航 4 项（产品/定价/客户/博客），hero 双按钮，3 特性段。Labels: 产品|定价|客户|博客",
};
const componentA = { name: "button-set", kind: "buttons", brief: "主/次/幽灵按钮三态" };
const componentB = { name: "input-set", kind: "inputs", brief: "默认/禁用/错误三态。Labels: 常规|禁用|错误" };

// --- template wiring: MIRROR the template ids in the Rust golden cases ------

const boardTemplates: Record<string, TemplateJson> = {
  "board-design-system": boardTemplateJson as TemplateJson,
  "brand-identity-lite": brandTemplateJson as TemplateJson,
};
const pageTemplates: Record<string, TemplateJson> = {
  "page-ui-standard": pageTemplateJson as TemplateJson,
  "page-landing-sections": landingTemplateJson as TemplateJson,
};
const componentTemplates: Record<string, TemplateJson> = {
  "component-sheet-grid": componentTemplateJson as TemplateJson,
};

function goldenCases(): Array<{ file: string; prompt: string }> {
  const out: Array<{ file: string; prompt: string }> = [];
  for (const [tag, project, page, component] of [
    ["a", projectA, pageA, componentA],
    ["b", projectB, pageB, componentB],
  ] as const) {
    for (const [id, template] of Object.entries(boardTemplates)) {
      out.push({ file: `${id}--${tag}.txt`, prompt: composeBoardPrompt(project, template) });
    }
    for (const [id, template] of Object.entries(pageTemplates)) {
      out.push({ file: `${id}--${tag}.txt`, prompt: composePagePrompt(project, page, template) });
    }
    for (const [id, template] of Object.entries(componentTemplates)) {
      out.push({
        file: `${id}--${tag}.txt`,
        prompt: composeComponentPrompt(project, component, template),
      });
    }
  }
  return out;
}

describe("prompt engine golden parity (Rust generates, TS must match)", () => {
  const cases = goldenCases();

  it("covers every builtin template × fixture pair (10 goldens)", () => {
    expect(cases).toHaveLength(10);
    for (const c of cases) {
      expect(fs.existsSync(path.join(GOLDENS_DIR, c.file)), `missing golden ${c.file}`).toBe(true);
    }
  });

  for (const c of goldenCases()) {
    it(`reproduces ${c.file} byte-for-byte`, () => {
      const golden = fs.readFileSync(path.join(GOLDENS_DIR, c.file), "utf8");
      expect(c.prompt).toBe(golden);
    });
  }
});
